const actionTypes = {
  //customer REGISTER ACTION TYPES
  EMAIL_REGISTER_START: "EMAIL_REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  // customer LOGIN ACTION TYPES
  EMAIL_LOGIN_START: "EMAIL_LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

    //customer fetch ACTIONS
  USER_FETCH_START: "USER_FETCH_START",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
  USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
  
  //set current user
  SET_USER_TOKEN: "SET_USER_TOKEN",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  //customer SIGNOUT ACTIONS
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  CLEAR_USER_ERROR: "CLEAR_USER_ERROR",

  //customer posts delet ACTIONS
  POST_DELETE_START: "POST_DELETE_START",
  POST_DELETE_SUCCESS: "POST_DELETE_SUCCESS",
  POST_DELETE_FAILURE: "POST_DELETE_FAILURE",

  //customer posts publish ACTIONS
  POST_PUBLISH_START: "POST_PUBLISH_START",
  POST_PUBLISH_SUCCESS: "POST_PUBLISH_SUCCESS",
  POST_PUBLISH_FAILURE: "POST_PUBLISH_FAILURE",

   //customer posts fetch ACTIONS
  POST_FETCH_START: "POST_FETCH_START",
  POST_FETCH_SUCCESS: "POST_FETCH_SUCCESS",
  POST_FETCH_FAILURE: "POST_FETCH_FAILURE",


};

export default actionTypes;
